### ISSUE TITLE
track query

### ISSUE THREAD

**Issue by Leonhard-Euler-ai** [GXNU-ZhongLab/ODTrack#5]
Hello, for training, why is the track query defined in the method `__init__`  of `ODTrack` instead of the `forward` method?
This will result in the query being empty only in the first step for training.

**Comment by AlexDotHam** [comment]
飞哥，你复现了吗？感觉这代码靠谱不

**Comment by jiaxianxin** [comment]
复现基本都差了10个点儿以上，就很离谱

**Comment by Leonhard-Euler-ai** [comment]
> 复现基本都差了10个点儿以上，就很离谱

你复现时改代码了吗

**Comment by jiaxianxin** [comment]
作者，您好！
代码一点儿没动，用的两张4090训练的权重，四个数据集训练的权重，推理出来在lasot是这个结果


在got10k是这个结果


| |
13023660221
|
|
***@***.***
|
---- Replied Message ----
| From | Hangfei ***@***.***> |
| Date | 3/8/2024 16:47 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [GXNU-ZhongLab/ODTrack] track query (Issue #5) |

复现基本都差了10个点儿以上，就很离谱

你复现时改代码了吗

**Comment by zxyyxzz** [comment]
> > 复现基本都差了10个点儿以上，就很离谱
> 
> 你复现时改代码了吗

改了后能复现不，那个Track_query明显就写的有问题，应该放在forward函数里。

**Comment by jiaxianxin** [comment]
代码一点儿没动哦，直接拿过来配好环境就跑的
---- Replied Message ----
| From | ***@***.***> |
| Date | 03/09/2024 11:24 |
| To | GXNU-ZhongLab/ODTrack ***@***.***> |
| Cc | jiaxianxin ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [GXNU-ZhongLab/ODTrack] track query (Issue #5) |

复现基本都差了10个点儿以上，就很离谱

你复现时改代码了吗

改了后能复现不，那个Track_query明显就写的有问题，应该放在forward函数里。

**Comment by Leonhard-Euler-ai** [comment]
改了forward中的track_query也复现不出来
直接用给的权重测试也不如论文的精度

**Comment by jiaxianxin** [comment]
你复现精度差了多少？

---- Replied Message ----
| From | Hangfei ***@***.***> |
| Date | 03/09/2024 11:35 |
| To | GXNU-ZhongLab/ODTrack ***@***.***> |
| Cc | jiaxianxin ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [GXNU-ZhongLab/ODTrack] track query (Issue #5) |

改了forward中的track_query也复现不出来
直接用给的权重测试也不如论文的精度

**Comment by zxyyxzz** [comment]
> 改了forward中的track_query也复现不出来
> 直接用给的权重测试也不如论文的精度

大概差几个点？

**Comment by jiaxianxin** [comment]
我这都差10个甚至十几个，你复现差多少

---- Replied Message ----
| From | ***@***.***> |
| Date | 03/09/2024 11:39 |
| To | GXNU-ZhongLab/ODTrack ***@***.***> |
| Cc | jiaxianxin ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [GXNU-ZhongLab/ODTrack] track query (Issue #5) |

改了forward中的track_query也复现不出来
直接用给的权重测试也不如论文的精度

大概差几个点？

**Comment by zxyyxzz** [comment]
****

> 我这都差10个甚至十几个，你复现差多少
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 03/09/2024 11:39 | | To | GXNU-ZhongLab/ODTrack ***@***.***> | | Cc | jiaxianxin ***@***.***>, Comment ***@***.***> | | Subject | Re: [GXNU-ZhongLab/ODTrack] track query (Issue #5) | 改了forward中的track_query也复现不出来 直接用给的权重测试也不如论文的精度 大概差几个点？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

也差10个，现在我把track_query改一下训一下看看结果，不过按照@Leonhard-Euler-ai所提到的，即使改了track_query也复现不了。

**Comment by Midkey** [comment]
我这也直接改成256的搜索区域跑的GOT，base模型结果只有70.0 AO。论文里用的384的尺寸可是能跑77.0的AO....

**Comment by WhiteButterflies** [comment]
![Screenshot 2024-04-01 at 16 28 10](https://github.com/GXNU-ZhongLab/ODTrack/assets/45557696/d09d6f86-5214-4c0f-91a0-718f02745031)
我在OTB上跑的
前两个是官方权重，最后ori后缀是官方的结果文件。

**Comment by marico2020** [comment]
> ![Screenshot 2024-04-01 at 16 28 10](https://private-user-images.githubusercontent.com/45557696/318382347-d09d6f86-5214-4c0f-91a0-718f02745031.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTUzNTEsIm5iZiI6MTcxMTk5NTA1MSwicGF0aCI6Ii80NTU1NzY5Ni8zMTgzODIzNDctZDA5ZDZmODYtNTIxNC00YzBmLTkxYTAtNzE4ZjAyNzQ1MDMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDE4MTA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4OGFmOTdmM2E5MWFlMzE5OTNiZWE3ODg3ZWMyYTA2MTU4Y2I3ZTM2YWQ5YmJiM2RlMDVjNzhjODZmNjA3YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7pm2kMeYk8Sw5jSo6vcny6KIq90KRlZp-N317GC2fmM) 我在OTB上跑的 前两个是官方权重，最后ori后缀是官方的结果文件。

我改了代码 OTB可以跑到72.9

**Comment by marico2020** [comment]
> > > ![Screenshot 2024-04-01 at 16 28 10](https://private-user-images.githubusercontent.com/45557696/318382347-d09d6f86-5214-4c0f-91a0-718f02745031.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTUzNTEsIm5iZiI6MTcxMTk5NTA1MSwicGF0aCI6Ii80NTU1NzY5Ni8zMTgzODIzNDctZDA5ZDZmODYtNTIxNC00YzBmLTkxYTAtNzE4ZjAyNzQ1MDMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDE4MTA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4OGFmOTdmM2E5MWFlMzE5OTNiZWE3ODg3ZWMyYTA2MTU4Y2I3ZTM2YWQ5YmJiM2RlMDVjNzhjODZmNjA3YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7pm2kMeYk8Sw5jSo6vcny6KIq90KRlZp-N317GC2fmM) 我在OTB上跑的 前两个是官方权重，最后ori后缀是官方的结果文件。
> > 
> > 
> > 我改了代码 OTB可以跑到72.9
> 
> 怎么做到的？求代码

哈哈 我这个是大改 把track_query全部去掉了

**Comment by liujue0825** [comment]
> > > > ![Screenshot 2024-04-01 at 16 28 10](https://private-user-images.githubusercontent.com/45557696/318382347-d09d6f86-5214-4c0f-91a0-718f02745031.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTUzNTEsIm5iZiI6MTcxMTk5NTA1MSwicGF0aCI6Ii80NTU1NzY5Ni8zMTgzODIzNDctZDA5ZDZmODYtNTIxNC00YzBmLTkxYTAtNzE4ZjAyNzQ1MDMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDE4MTA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4OGFmOTdmM2E5MWFlMzE5OTNiZWE3ODg3ZWMyYTA2MTU4Y2I3ZTM2YWQ5YmJiM2RlMDVjNzhjODZmNjA3YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7pm2kMeYk8Sw5jSo6vcny6KIq90KRlZp-N317GC2fmM) 我在OTB上跑的 前两个是官方权重，最后ori后缀是官方的结果文件。
> > > 
> > > 
> > > 我改了代码 OTB可以跑到72.9
> > 
> > 
> > 怎么做到的？求代码
> 
> 哈哈 我这个是大改 把track_query全部去掉了

同求份代码，佬

**Comment by Wanggggggggggggggg** [comment]
> > > > ![Screenshot 2024-04-01 at 16 28 10](https://private-user-images.githubusercontent.com/45557696/318382347-d09d6f86-5214-4c0f-91a0-718f02745031.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTUzNTEsIm5iZiI6MTcxMTk5NTA1MSwicGF0aCI6Ii80NTU1NzY5Ni8zMTgzODIzNDctZDA5ZDZmODYtNTIxNC00YzBmLTkxYTAtNzE4ZjAyNzQ1MDMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDE4MTA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4OGFmOTdmM2E5MWFlMzE5OTNiZWE3ODg3ZWMyYTA2MTU4Y2I3ZTM2YWQ5YmJiM2RlMDVjNzhjODZmNjA3YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7pm2kMeYk8Sw5jSo6vcny6KIq90KRlZp-N317GC2fmM)我在OTB上跑的 前两个是官方权重，最后ori后缀是官方的结果文件。
> > > 
> > > 
> > > 我改了代码 OTB可以跑到72.9
> > 
> > 
> > 怎么做到的？求代码
> 
> 哈哈 我这个是大改 把track_query全部去掉了

同求 佬
