### ISSUE TITLE
Problem with evaluation.

### ISSUE THREAD

**Issue by LuoXubo** [GXNU-ZhongLab/ODTrack#9]
Hi!

Thanks for your great work. I'm trying to test ODTrack on the GOT-10k. Could you provide the trained weights of ODTrack?

**Comment by Azong-HQU** [comment]
Hi, the link to the ODTrack model is below: [[Models](https://drive.google.com/drive/folders/17LacrfRO01R75bxU4bgA87eo1b_rX5Gj?usp=sharing)], [[Raw Results](https://drive.google.com/drive/folders/10I7aHb2J4SFTMuQ_LN33VbaiykD_M2hi?usp=sharing)], [[Training logs](https://drive.google.com/drive/folders/1BXnYmnGnSZIA0IR_gwdlDczl0ex4DgFF?usp=sharing)]

**Comment by LuoXubo** [comment]
Thanks a lot! I'll close this issue : )
